development:
ID_GRUPO: '590baa00d6b4ec0004902469'
ID_CUENTA_BANCO: '590baa00d6b4ec0004902470'
CLAVE_BODEGA: '2T02j&xwE#tQA#e'
USUARIO_COMPRA_EM_LINEA: 'grupo8'
CONTRASENA_COMPRA_EM_LINEA: '0pPfDeRT'
URL_API_BODEGA: 'https://integracion-2017-dev.herokuapp.com/bodega/'
URL_API_OC: 'https://integracion-2017-dev.herokuapp.com/oc/'
