development:
ID_GRUPO: '590baa00d6b4ec0004902469'
ID_CUENTA_BANCO: '590baa00d6b4ec0004902470'
CLAVE_BODEGA: '2T02j&xwE#tQA#e'
USUARIO_COMPRA_EM_LINEA: 'grupo8'
CONTRASENA_COMPRA_EM_LINEA: '0pPfDeRT'
URL_API_BODEGA: 'https://integracion-2017-dev.herokuapp.com/bodega/'
URL_API_OC: 'https://integracion-2017-dev.herokuapp.com/oc/'
BODEGA_GENERAL: '590baa77d6b4ec0004902cbf'
BODEGA_GENERAL_2: '590baa77d6b4ec0004902ea4'
BODEGA_RECEPCION: '590baa77d6b4ec0004902cbd'
BODEGA_DESPACHO: '590baa77d6b4ec0004902cbe'
BODEGA_PULMON: '590baa77d6b4ec0004902ea5'

#api_b2b
ID_GRUPO1: '590baa00d6b4ec0004902462'
ID_GRUPO2: '590baa00d6b4ec0004902463'
ID_GRUPO3: '590baa00d6b4ec0004902464'
ID_GRUPO4: '590baa00d6b4ec0004902465'
ID_GRUPO5: '590baa00d6b4ec0004902466'
ID_GRUPO6: '590baa00d6b4ec0004902467'
ID_GRUPO7: '590baa00d6b4ec0004902468'

URL_GRUPO1: 'dev.integra17-1.ing.puc.cl/api'
URL_GRUPO2: 'dev.integra17-2.ing.puc.cl'
URL_GRUPO3: 'dev.integra17-3.ing.puc.cl'
URL_GRUPO4: 'dev.integra17-4.ing.puc.cl'
URL_GRUPO5: 'dev.integra17-5.ing.puc.cl'
URL_GRUPO6: 'dev.integra17-6.ing.puc.cl'
URL_GRUPO7: 'dev.integra17-7.ing.puc.cl/api'


#api_banco
CUENTA_FABRICA:  "590baa00d6b4ec0004902460"
CUENTA_BANCO: "590baa00d6b4ec0004902470"
URL_PAGO_TRANSFERENCIA: 'https://integracion-2017-dev.herokuapp.com/banco'

#api_orden_compra
API_URL_OC: 'https://integracion-2017-dev.herokuapp.com/oc/'


#api_pago
API_URL_PAGO: 'https://integracion-2017-dev.herokuapp.com/web/'
URL_PAY_PROXY: 'http://localhost:3000/payproxies/'
API_URL_FACTURAS: 'https://integracion-2017-dev.herokuapp.com/sii/' ##Produccion

SPREE_API_KEY: "234c9658f8a875bc61a06ce83c058feb5340777ee9df14ff"
API_URL_SPREE: "http://integra17-8.ing.puc.cl/api/v1/"

#SPREE_API_KEY: "a685e0757f4d0175ce1a17a924a330bfdcf8a939216171f0"
#API_URL_SPREE: "http://localhost:4000/api/v1/"